"""Consult & Healing — Adaptive Assessment API.

Endpoints:
  POST /api/consult/start                         → create session, return first node
  GET  /api/consult/{session_id}                  → current node payload + session state
  POST /api/consult/{session_id}/answer           → submit answers, return next node
  GET  /api/consult/{session_id}/generate-profile → return pre-computed profile + summary
  GET  /api/consult/profiles/all                  → list user's completed profiles
  GET  /api/consult/profiles/{profile_id}         → single completed profile

Summary is generated by a rule-based engine at assessment completion — no AI, no API key.
"""

from __future__ import annotations

import json
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy.orm import Session

from core.database import get_db
from core.deps import get_current_user
from models.orm import AssessmentProfile, AssessmentSession, User
from services import assessment_service as svc

router = APIRouter()


# ── Schemas ───────────────────────────────────────────────────────────────────

class AnswerSubmission(BaseModel):
    node_id: str
    answers: dict[str, float]        # {question_id: numeric_value}
    text_values: dict[str, str] = {} # {question_id: display text} — optional




# ── Routes ────────────────────────────────────────────────────────────────────

@router.post("/start", status_code=status.HTTP_201_CREATED)
def start_session(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Create a new assessment session and return the first node (domain selector)."""
    session = svc.create_session(user_id=user.id, db=db)
    node_payload = svc.build_node_payload(svc.ENTRY_NODE, db)
    return {
        "session_id": session.id,
        "node":       node_payload,
    }


@router.get("/{session_id}")
def get_current_node(
    session_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Return the current node for an in-progress session — allows resuming."""
    try:
        session = svc.get_session(session_id, user.id, db)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    if session.status == "completed":
        profile = db.query(AssessmentProfile).filter_by(session_id=session_id).first()
        return {
            "session_id": session.id,
            "status":     "completed",
            "profile":    json.loads(profile.profile_json) if profile else None,
            "ai_summary": profile.ai_summary if profile else None,
        }

    node_payload = svc.build_node_payload(session.current_node_id, db)
    return {
        "session_id": session.id,
        "status":     session.status,
        "flags":      json.loads(session.flags_json),
        "node":       node_payload,
    }


@router.post("/{session_id}/answer")
def submit_answer(
    session_id: int,
    body: AnswerSubmission,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Submit answers for the current node. Returns the next node or done=True."""
    try:
        session = svc.get_session(session_id, user.id, db)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    if session.status == "completed":
        raise HTTPException(status_code=400, detail="Session already completed")

    if body.node_id != session.current_node_id:
        raise HTTPException(
            status_code=400,
            detail=f"Expected answers for node '{session.current_node_id}', got '{body.node_id}'",
        )

    try:
        result = svc.submit_answers(
            session=session,
            node_id=body.node_id,
            answers=body.answers,
            text_values=body.text_values,
            db=db,
        )
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))

    # Safety item triggered — always include crisis flag regardless of routing
    if result.get("safety_triggered"):
        result["crisis_resources"] = {
            "thailand":      "1323 (กรมสุขภาพจิต, 24 ชม.)",
            "international": "https://findahelpline.com",
        }

    return {"session_id": session_id, **result}


@router.get("/{session_id}/generate-profile")
def get_profile_summary(
    session_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    """Return the pre-computed profile and rule-based summary.

    The summary is generated instantly at assessment completion by the Python
    scoring engine — no AI, no API key required. This endpoint just retrieves it.
    """
    try:
        session = svc.get_session(session_id, user.id, db)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))

    if session.status != "completed":
        raise HTTPException(status_code=400, detail="Assessment not yet completed")

    profile_row = db.query(AssessmentProfile).filter_by(session_id=session_id).first()
    if not profile_row:
        raise HTTPException(status_code=404, detail="Profile not found")

    return {
        "session_id": session_id,
        "profile":    json.loads(profile_row.profile_json),
        "ai_summary": profile_row.ai_summary,
    }


@router.get("/profiles/all")
def list_profiles(
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> list[dict[str, Any]]:
    """List all completed assessment profiles for the current user."""
    rows = (
        db.query(AssessmentProfile)
        .filter_by(user_id=user.id)
        .order_by(AssessmentProfile.created_at.desc())
        .all()
    )
    return [
        {
            "profile_id":  r.id,
            "session_id":  r.session_id,
            "created_at":  r.created_at.isoformat(),
            "has_summary": bool(r.ai_summary),
            "profile":     json.loads(r.profile_json),
        }
        for r in rows
    ]


@router.get("/profiles/{profile_id}")
def get_profile(
    profile_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> dict[str, Any]:
    row = db.query(AssessmentProfile).filter_by(id=profile_id, user_id=user.id).first()
    if not row:
        raise HTTPException(status_code=404, detail="Profile not found")
    return {
        "profile_id":  row.id,
        "session_id":  row.session_id,
        "created_at":  row.created_at.isoformat(),
        "profile":     json.loads(row.profile_json),
        "ai_summary":  row.ai_summary,
    }


